### PR TITLE
[BT-659] Update to Node.js 16

### PR DESCRIPTION
**Pull request by breilly2**
https://broadworkbench.atlassian.net/browse/BT-659

Also:

* Update dependencies for security
* Remove never-deployed cloud function code (to remove an outdated/irrelevant source of dependencies)

I reviewed the changelogs on all of the dependencies to watch out for breaking changes. In most cases, there was nothing significant other than removing support for Node.js 10. A couple of notes:

* Joi (which moved from `@hapi/joi` to `joi`) had a few breaking changes listed in the [changelog](https://joi.dev/resources/changelog/). They helpfully note versions containing breaking changes, such as 17.2.0. Reviewing these gave me no cause for concern. In particular, I was reassured by notes like [this](https://github.com/sideway/joi/issues/2284#issuecomment-653958119) explaining the justification for marking something as a breaking change. The explanation is very thoughtful and empathetic to different ways in which people may be using the library, which gives me high confidence in the accuracy of the "breaking changes" tags. ~I will create a tech-debt ticket to create some unit tests around the use of Joi to increase our confidence.~ Edit: Created [BT-694](https://broadworkbench.atlassian.net/browse/BT-694)
* Updating `node-fetch` from 2.x to 3.x is non-trivial. In the interest of getting this done quickly, I opted to not tackle this update right now. ~I will create a tech-debt ticket for this update.~ Edit: Created [BT-695](https://broadworkbench.atlassian.net/browse/BT-695)

I tested this by running Bard locally, running Terra UI locally (pointed at my local Bard), clicking around the UI, and making sure that events get logged to Mixpanel and no errors show up in the Bard logs.

### CODE REVIEW

**Comment by breilly2** [comment]
I've added more reviewers than I need, but wanted to increase visibility of these updates. In particular, @petesantos might have thoughts about anything to watch out for with our use of Joi and @eweitz might want to make sure nothing here breaks SCP's use of Bard.

**Review by kraefrei — APPROVED** [review]
LGTM, would it make sense to linking the tech debt tickets in the ticket so we can track those upgrades?

**Review by petesantos — APPROVED** [review]

**Comment by petesantos** [comment]
Thanks for doing this!

**Comment by breilly2** [comment]
GitHub is still expecting build-cloud-function to pass even though that part of the config is gone. I'm going to close and re-open to see if that clears it up.

**Review by kraefrei — APPROVED** [review]

**Comment by breilly2** [comment]
Closing this and opening a new PR to clear the never-to-be-fulfilled requirement on build-cloud-function.

**Pull request closed without merging**
